Set
oWS
=
CreateObject
WScript.Shell
sLinkFile
=
C:\Users\Administrator\Desktop\OpenCode.lnk
oLink.TargetPath
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor\OpenCode.bat
oLink.WorkingDirectory
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor
oLink.Save
Set
oLink
=
oWS.CreateShortcut
C:\Users\Administrator\Desktop\OpenCode Llama.lnk
oLink.TargetPath
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor\OpenCode.bat
oLink.Arguments
=
llama
oLink.WorkingDirectory
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor
oLink.Save
Set
oLink
=
oWS.CreateShortcut
C:\Users\Administrator\Desktop\OpenCode Gemini.lnk
oLink.TargetPath
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor\OpenCode.bat
oLink.Arguments
=
gemini
oLink.WorkingDirectory
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor
oLink.Save
Set
oLink
=
oWS.CreateShortcut
C:\Users\Administrator\Desktop\OpenCode Ollama.lnk
oLink.TargetPath
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor\OpenCode.bat
oLink.Arguments
=
ollama
oLink.WorkingDirectory
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor
oLink.Save
Set
oLink
=
oWS.CreateShortcut
C:\Users\Administrator\Desktop\OpenCode Academix.lnk
oLink.TargetPath
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor\OpenCode.bat
oLink.Arguments
=
academix
oLink.WorkingDirectory
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor
oLink.Save
Set
oLink
=
oWS.CreateShortcut
C:\Users\Administrator\Desktop\OpenCode Picker.lnk
oLink.TargetPath
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor\OpenCode.bat
oLink.Arguments
=
picker
oLink.WorkingDirectory
=
C:\Users\Administrator\Dropbox\Logistics.Public.Sector.Refactor
oLink.Save
