"""add-page-numbers.py — Academix v13.2
Adds section breaks and page numbering to the thesis DOCX:
- Pre-chapters (cover → فهرس → قائمة الجداول → المقدمة): Arabic Abjad letters (أ، ب، ج...)
- Main body (الفصل الأول → الملاحق): Arabic numerals (1, 2, 3...)
- Footer on all pages showing page number
"""

import sys, copy, os, tempfile
from docx import Document
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'


def set_pgnum_type(sectPr, fmt='decimal'):
    """Set page number format on a sectPr element."""
    pgn = sectPr.find(f'{W}pgNumType')
    if pgn is None:
        pgn = OxmlElement('w:pgNumType')
        sectPr.append(pgn)
    pgn.set(f'{W}fmt', fmt)


def add_footer_with_page(doc):
    """Add page number footer to all sections using low-level XML."""
    for i, section in enumerate(doc.sections):
        sectPr = section._sectPr
        # Create footer reference
        footer = section.footer
        footer.is_linked_to_previous = False
        p = footer.paragraphs[0]
        p.alignment = 2  # center
        p.clear()

        # Build field: PAGE
        # begin
        r1 = OxmlElement('w:r')
        r1Pr = OxmlElement('w:rPr')
        r1.append(r1Pr)
        fc1 = OxmlElement('w:fldChar')
        fc1.set(f'{W}fldCharType', 'begin')
        r1.append(fc1)
        p._p.append(r1)

        # instruction
        r2 = OxmlElement('w:r')
        r2Pr = OxmlElement('w:rPr')
        r2.append(r2Pr)
        instr = OxmlElement('w:instrText')
        instr.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
        instr.text = 'PAGE'
        r2.append(instr)
        p._p.append(r2)

        # separate
        r3 = OxmlElement('w:r')
        r3Pr = OxmlElement('w:rPr')
        r3.append(r3Pr)
        fc2 = OxmlElement('w:fldChar')
        fc2.set(f'{W}fldCharType', 'separate')
        r3.append(fc2)
        p._p.append(r3)

        # placeholder
        r4 = OxmlElement('w:r')
        r4Pr = OxmlElement('w:rPr')
        r4.append(r4Pr)
        t = OxmlElement('w:t')
        t.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
        t.text = '1'
        r4.append(t)
        p._p.append(r4)

        # end
        r5 = OxmlElement('w:r')
        r5Pr = OxmlElement('w:rPr')
        r5.append(r5Pr)
        fc3 = OxmlElement('w:fldChar')
        fc3.set(f'{W}fldCharType', 'end')
        r5.append(fc3)
        p._p.append(r5)


def main():
    if len(sys.argv) < 2:
        print("Usage: python add-page-numbers.py <docx_path>")
        sys.exit(1)

    path = sys.argv[1]
    print(f"Adding page numbering in: {path}")

    doc = Document(path)
    body = doc.element.body

    # Find الفصل الأول paragraph index in body children
    ch1_idx = None
    for i, child in enumerate(body):
        if child.tag != f'{W}p':
            continue
        text = ''.join(t.text or '' for t in child.iter(f'{W}t'))
        if 'الفصل الأول' in text:
            ch1_idx = i
            break

    if ch1_idx is None:
        print("[ERROR] الفصل الأول not found")
        sys.exit(1)

    print(f"  الفصل الأول at body child index {ch1_idx}")

    # Strategy: Insert a section break by adding a sectPr to the
    # paragraph BEFORE الفصل الأول. The OOXML spec says each w:sectPr
    # ends a section; the LAST w:sectPr in the body defines the final section.

    # 1. Remove the existing trailing sectPr (auto-generated by pandoc/python-docx)
    existing_sects = body.findall(f'{W}sectPr')
    trailing_sectPr = None
    for sp in existing_sects:
        # Keep only the last one
        if sp == body[-1] or sp == list(body)[-1]:
            trailing_sectPr = sp
            break
    # Actually, find the actual last sectPr
    last_elem = list(body)[-1]
    if last_elem.tag == f'{W}sectPr':
        trailing_sectPr = last_elem
    else:
        for sp in existing_sects:
            if sp == list(body)[-1]:
                trailing_sectPr = sp
                break

    if trailing_sectPr is not None:
        body.remove(trailing_sectPr)
        print("  Removed trailing sectPr")
    else:
        print("  [WARN] No trailing sectPr found, creating one")
        trailing_sectPr = OxmlElement('w:sectPr')

    # 2. Clone the sectPr for the first section (pre-chapters)
    # Insert a copy right before الفصل الأول paragraph
    pre_sectPr = copy.deepcopy(trailing_sectPr)
    # The sectPr goes INSIDE the last paragraph's pPr of the first section.
    # We need to insert it into the paragraph BEFORE الفصل الأول.
    pre_chapter_para_idx = ch1_idx - 1
    pre_para = list(body)[pre_chapter_para_idx]

    if pre_para.tag == f'{W}p':
        pPr = pre_para.find(f'{W}pPr')
        if pPr is None:
            pPr = OxmlElement('w:pPr')
            pre_para.insert(0, pPr)
        # Remove any existing sectPr in this pPr
        old = pPr.find(f'{W}sectPr')
        if old is not None:
            pPr.remove(old)
        pPr.append(pre_sectPr)
        print(f"  Section break inserted before الفصل الأول (between child {pre_chapter_para_idx} and {ch1_idx})")

    # 3. Append trailing sectPr at end of body for section 2
    body.append(trailing_sectPr)

    # Save and reload to get fresh section references
    tmp = tempfile.NamedTemporaryFile(suffix='.docx', delete=False)
    tmp.close()
    doc.save(tmp.name)
    doc2 = Document(tmp.name)

    # 4. Add page number footers to both sections
    add_footer_with_page(doc2)

    # 5. Set page number formats (AFTER footer, to avoid sectPr replacement)
    sec0 = doc2.sections[0]
    sp0 = sec0._sectPr
    set_pgnum_type(sp0, 'arabicAbjad')
    print(f"  Section 0 (pre-chapters): Arabic Abjad numbering")

    if len(doc2.sections) > 1:
        sec1 = doc2.sections[1]
        sp1 = sec1._sectPr
        set_pgnum_type(sp1, 'decimal')
        print(f"  Section 1 (body): Arabic numeral numbering")
    else:
        print(f"  [WARN] Only 1 section found")

    doc2.save(path)
    os.unlink(tmp.name)
    print(f"  Page footers added")
    print(f"Saved: {path}")


if __name__ == '__main__':
    main()
