"""add-page-numbers.py — Academix v13.2
Adds section breaks and page numbering to the thesis DOCX:
- Pre-chapters (cover → فهرس → قائمة الجداول → المقدمة): Arabic Abjad letters (أ، ب، ج...)
- Main body (الفصل الأول → الملاحق): Arabic numerals (1, 2, 3...)
- Footer on all pages showing page number
Cover sectPr is stripped in prepend-cover.py so it doesn't create extra sections.
"""

import sys, copy, os, tempfile
from docx import Document
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'


def set_pgnum_type(sectPr, fmt='decimal'):
    """Set page number format on a sectPr element."""
    pgn = sectPr.find(f'{W}pgNumType')
    if pgn is None:
        pgn = OxmlElement('w:pgNumType')
        sectPr.append(pgn)
    pgn.set(f'{W}fmt', fmt)


def add_footer_with_page(doc):
    """Add page number footer to all sections using low-level XML."""
    for i, section in enumerate(doc.sections):
        sectPr = section._sectPr
        # Create footer reference
        footer = section.footer
        footer.is_linked_to_previous = False
        p = footer.paragraphs[0]
        p.alignment = 2  # center
        p.clear()

        # Build field: PAGE
        # begin
        r1 = OxmlElement('w:r')
        r1Pr = OxmlElement('w:rPr')
        r1.append(r1Pr)
        fc1 = OxmlElement('w:fldChar')
        fc1.set(f'{W}fldCharType', 'begin')
        r1.append(fc1)
        p._p.append(r1)

        # instruction
        r2 = OxmlElement('w:r')
        r2Pr = OxmlElement('w:rPr')
        r2.append(r2Pr)
        instr = OxmlElement('w:instrText')
        instr.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
        instr.text = 'PAGE'
        r2.append(instr)
        p._p.append(r2)

        # separate
        r3 = OxmlElement('w:r')
        r3Pr = OxmlElement('w:rPr')
        r3.append(r3Pr)
        fc2 = OxmlElement('w:fldChar')
        fc2.set(f'{W}fldCharType', 'separate')
        r3.append(fc2)
        p._p.append(r3)

        # placeholder
        r4 = OxmlElement('w:r')
        r4Pr = OxmlElement('w:rPr')
        r4.append(r4Pr)
        t = OxmlElement('w:t')
        t.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
        t.text = '1'
        r4.append(t)
        p._p.append(r4)

        # end
        r5 = OxmlElement('w:r')
        r5Pr = OxmlElement('w:rPr')
        r5.append(r5Pr)
        fc3 = OxmlElement('w:fldChar')
        fc3.set(f'{W}fldCharType', 'end')
        r5.append(fc3)
        p._p.append(r5)


def main():
    if len(sys.argv) < 2:
        print("Usage: python add-page-numbers.py <docx_path>")
        sys.exit(1)

    path = sys.argv[1]
    print(f"Adding page numbering in: {path}")

    doc = Document(path)
    body = doc.element.body

    # Find الفصل الأول paragraph index in body children
    ch1_idx = None
    for i, child in enumerate(body):
        if child.tag != f'{W}p':
            continue
        text = ''.join(t.text or '' for t in child.iter(f'{W}t'))
        if 'الفصل الأول' in text:
            ch1_idx = i
            break

    if ch1_idx is None:
        print("[ERROR] الفصل الأول not found")
        sys.exit(1)

    print(f"  الفصل الأول at body child index {ch1_idx}")

    # Strategy: Insert a section break by adding a w:sectPr as a DIRECT child
    # of w:body before الفصل الأول. python-docx only recognizes w:sectPr
    # that are direct body children (not nested inside pPr).
    #
    # OOXML: each w:sectPr ends a section, the LAST one defines final section.
    # Body structure after fix:
    #   [pre-chapter content P0...Pn-1] [sectPr_pre] [الفصل الأول Pn...] [sectPr_body]
    #   Section 0: pre-chapters (Abjad)
    #   Section 1: body (Arabic numerals)

    # 1. Remove existing trailing sectPr (auto-generated by pandoc/python-docx)
    last_elem = list(body)[-1]
    trailing_sectPr = None
    if last_elem.tag == f'{W}sectPr':
        trailing_sectPr = last_elem
        body.remove(trailing_sectPr)
        print("  Removed trailing sectPr")
    else:
        for sp in body.findall(f'{W}sectPr'):
            if sp == list(body)[-1]:
                trailing_sectPr = sp
                body.remove(sp)
                print("  Removed trailing sectPr (found mid-body)")
                break

    if trailing_sectPr is None:
        print("  [WARN] No trailing sectPr found, creating one")
        trailing_sectPr = OxmlElement('w:sectPr')

    # 2. Clone the sectPr for pre-chapter section
    pre_sectPr = copy.deepcopy(trailing_sectPr)
    set_pgnum_type(pre_sectPr, 'arabicAbjad')

    # 3. Insert pre_sectPr as DIRECT body child before الفصل الأول
    ch1_element = list(body)[ch1_idx]
    body.insert(list(body).index(ch1_element), pre_sectPr)
    print(f"  Section break inserted before الفصل الأول (at body child index {ch1_idx})")

    # 4. Append body section sectPr at end
    set_pgnum_type(trailing_sectPr, 'decimal')
    body.append(trailing_sectPr)

    # Save and reload to get fresh section references
    tmp = tempfile.NamedTemporaryFile(suffix='.docx', delete=False)
    tmp.close()
    doc.save(tmp.name)
    doc2 = Document(tmp.name)

    # 5. Add page number footers to all sections
    add_footer_with_page(doc2)

    # 6. Verify sections
    sec_count = len(doc2.sections)
    print(f"  Sections found: {sec_count}")
    for si in range(sec_count):
        sp = doc2.sections[si]._sectPr
        pgn = sp.find(f'{W}pgNumType')
        current = pgn.get(f'{W}fmt') if pgn is not None else 'none'
        print(f"  Section {si}: pgNumType={current}")

    doc2.save(path)
    os.unlink(tmp.name)
    print(f"  Page footers added")
    print(f"Saved: {path}")


if __name__ == '__main__':
    main()
